name = "orimi-checkout"
compatibility_date = "2023-12-01"

# [vars]
#  API_SECRET_STRIPE = "sk_test_51PN1TIDxuq8uXEJzJs6tuFzz8EzMX3ryFg7dnJ6C0kyTC6dieFqGRN5oH7gUFgs1asx81RlN4vbspzjyTX3gtm5s00uMJXegPw"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"